In [1]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "p_id": [101, 102, 103, 104],
    "p_name": ["QWE", "SDF", "RTY", "RFV"],
    "Sales": [5000, 8000, 4000, 6000],
    "Amount": [20000, 78000, 45000, 96000],
}
df = pd.DataFrame(data)
df

   p_id p_name  Sales  Amount
0   101    QWE   5000   20000
1   102    SDF   8000   78000
2   103    RTY   4000   45000
3   104    RFV   6000   96000

In [13]:
df.loc[0] # First row display

p_id        101
p_name      QWE
Sales      5000
Amount    20000
Name: 0, dtype: object

In [14]:
df.loc[0, "Sales"] # 0 Row and only sales data

5000

In [15]:
df.loc[:, ["p_name", "Sales"]] # all Row selected Columns

  p_name  Sales
0    QWE   5000
1    SDF   8000
2    RTY   4000
3    RFV   6000

In [16]:
df.loc[1:3] # 1 to 3 row display

   p_id p_name  Sales  Amount
1   102    SDF   8000   78000
2   103    RTY   4000   45000
3   104    RFV   6000   96000

In [17]:
df.loc[1:3, ["p_id", "Amount"]] # 1 to 3 row and selected Columns

   p_id  Amount
1   102   78000
2   103   45000
3   104   96000

In [22]:
df.iloc[0, 3]

20000

In [23]:
df.iloc[:, [2, 3]]

   Sales  Amount
0   5000   20000
1   8000   78000
2   4000   45000
3   6000   96000

In [24]:
df.iloc[1:3]

   p_id p_name  Sales  Amount
1   102    SDF   8000   78000
2   103    RTY   4000   45000

In [25]:
df.iloc[1:4]

   p_id p_name  Sales  Amount
1   102    SDF   8000   78000
2   103    RTY   4000   45000
3   104    RFV   6000   96000