In [11]:
import pandas as pd

In [12]:
# Import Data
df = pd.read_csv(r"D:\Data.csv")
df

   P_Id   P_Name    Category Branch          City   Sales   Profit
0   101     Pent    Clothing       a         Surat   15000   10000
1   102    Shirt    Clothing       b  Surendrnagar   10000    5000
2   103  T-Shirt    Clothing       a     Ahmedabad   20000    4000
3   104       Tv  Electronic       b         Surat   50000   15000
4   105    Phone  Electronic       a  Surendrnagar   41000   45000
5   106   Tablet  Electronic       b     Ahmedabad    4500     500

In [13]:
# Display First 5 data

df.head()

   P_Id   P_Name    Category Branch          City   Sales   Profit
0   101     Pent    Clothing       a         Surat   15000   10000
1   102    Shirt    Clothing       b  Surendrnagar   10000    5000
2   103  T-Shirt    Clothing       a     Ahmedabad   20000    4000
3   104       Tv  Electronic       b         Surat   50000   15000
4   105    Phone  Electronic       a  Surendrnagar   41000   45000

In [14]:
# Display last 5 data
df.tail()

   P_Id   P_Name    Category Branch          City   Sales   Profit
1   102    Shirt    Clothing       b  Surendrnagar   10000    5000
2   103  T-Shirt    Clothing       a     Ahmedabad   20000    4000
3   104       Tv  Electronic       b         Surat   50000   15000
4   105    Phone  Electronic       a  Surendrnagar   41000   45000
5   106   Tablet  Electronic       b     Ahmedabad    4500     500

In [15]:
# Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   P_Id      6 non-null      int64
 1   P_Name    6 non-null      object
 2   Category  6 non-null      object
 3   Branch    6 non-null      object
 4   City      6 non-null      object
 5   Sales     6 non-null      int64
 6   Profit    6 non-null      int64
dtypes: int64(3), object(4)
memory usage: 468.0+ bytes

In [16]:
# Display Sytatical Summary 
df.describe()

             P_Id        Sales        Profit
count    6.000000      6.000000      6.00000
mean   103.500000  23416.666667  13250.00000
std      1.870829  18089.822184  16357.71989
min    101.000000   4500.000000    500.00000
25%    102.250000  11250.000000   4250.00000
50%    103.500000  17500.000000   7500.00000
75%    104.750000  35750.000000  13750.00000
max    106.000000  50000.000000  45000.00000

In [17]:
# Display Shape of dataset
df.shape

(6, 7)

In [20]:
# Dispaly Selected Column 
df[["P_Name", "Sales "]]

    P_Name  Sales
0     Pent   15000
1    Shirt   10000
2  T-Shirt   20000
3       Tv   50000
4    Phone   41000
5   Tablet    4500

In [19]:
# Check All Columns
df.columns

Index(['P_Id', 'P_Name', 'Category', 'Branch ', 'City ', 'Sales ', 'Profit'], dtype='object')

In [25]:
# display All Product > 50000
df[df["Sales "] > 40000]

   P_Id P_Name    Category Branch          City   Sales   Profit
3   104     Tv  Electronic       b         Surat   50000   15000
4   105  Phone  Electronic       a  Surendrnagar   41000   45000

In [27]:
# display Electronic Category Only
df[df["Category"] == "Electronic"]

   P_Id  P_Name    Category Branch          City   Sales   Profit
3   104      Tv  Electronic       b         Surat   50000   15000
4   105   Phone  Electronic       a  Surendrnagar   41000   45000
5   106  Tablet  Electronic       b     Ahmedabad    4500     500

In [32]:
# Sort data in descending
df.sort_values(by = "Sales ", ascending=False)

   P_Id   P_Name    Category Branch          City   Sales   Profit
3   104       Tv  Electronic       b         Surat   50000   15000
4   105    Phone  Electronic       a  Surendrnagar   41000   45000
2   103  T-Shirt    Clothing       a     Ahmedabad   20000    4000
0   101     Pent    Clothing       a         Surat   15000   10000
1   102    Shirt    Clothing       b  Surendrnagar   10000    5000
5   106   Tablet  Electronic       b     Ahmedabad    4500     500

In [33]:
# Find the Total Sum of sales
df["Sales "].sum()

140500

In [34]:
# find Avg for profit
df["Profit"].mean()

13250.0

In [35]:
# maximum Sales 
df["Sales "].max()

50000

In [37]:
# profit Maximum
df["Profit"].max()

45000

In [39]:
# category wise sum
df.groupby("Category")["Sales "].sum()

Category
Clothing      45000
Electronic    95500
Name: Sales , dtype: int64

In [41]:
# Branch Wise avg profit
df.groupby("Branch ")["Profit"].mean()

Branch
a    19666.666667
b     6833.333333
Name: Profit, dtype: float64

In [43]:
# new column gst
# sales Gst count 18%
df["Gst"] = df["Sales "] * 0.18
df

   P_Id   P_Name    Category Branch          City   Sales   Profit     Gst
0   101     Pent    Clothing       a         Surat   15000   10000  2700.0
1   102    Shirt    Clothing       b  Surendrnagar   10000    5000  1800.0
2   103  T-Shirt    Clothing       a     Ahmedabad   20000    4000  3600.0
3   104       Tv  Electronic       b         Surat   50000   15000  9000.0
4   105    Phone  Electronic       a  Surendrnagar   41000   45000  7380.0
5   106   Tablet  Electronic       b     Ahmedabad    4500     500   810.0

In [44]:
# new Column net Sales
# sales + gst

df["Net_Sales"] = df["Gst"] + df["Sales "]
df

,P_Id,P_Name,Category,Branch,City,Sales,Profit,Gst,Net_Sales
0,101,Pent,Clothing,a,Surat,15000,10000,2700.0,17700.0
1,102,Shirt,Clothing,b,Surendrnagar,10000,5000,1800.0,11800.0
2,103,T-Shirt,Clothing,a,Ahmedabad,20000,4000,3600.0,23600.0
3,104,Tv,Electronic,b,Surat,50000,15000,9000.0,59000.0
4,105,Phone,Electronic,a,Surendrnagar,41000,45000,7380.0,48380.0
5,106,Tablet,Electronic,b,Ahmedabad,4500,500,810.0,5310.0